### ISSUE TITLE
Error if doing batch size > 1

### ISSUE THREAD

**Issue by fractal-fumbler** [kinfolk0117/ComfyUI_TiledIPAdapter#4]
hello :)

i usually do batch size = 4 to compare results of different seeds for prompt.
but when using batch size more than 1 i am getting error
```cannot reshape tensor of 0 elements into shape [0, -1, 16, 80] because the unspecified dimension size -1 can be any value and is ambiguous```

<details><summary>log </summary>

```python
2024-01-07 20:56:15,416 - root - ERROR - Traceback (most recent call last):                           
  File "/tmp/ComfyUI/execution.py", line 154, in recursive_execute                  
    output_data, output_ui = get_output_data(obj, input_data_all)                   
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                   
  File "/tmp/ComfyUI/execution.py", line 84, in get_output_data                     
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)                         
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                         
  File "/tmp/ComfyUI/execution.py", line 77, in map_node_over_list                  
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))             
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^              
  File "/tmp/ComfyUI/custom_nodes/ComfyUI_TiledIPAdapter/nodes.py", line 45, in process               
    foo = IPAdapterApply.apply_ipadapter(self, ipadapter, model, ipadapter_weight, clip_vision, image,  "original", 0.0, None, None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 618, in apply_ipadapter
    clip_embed = clip_vision.encode_image(image)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/comfy/clip_vision.py", line 50, in encode_image
    out = self.model(pixel_values=pixel_values, intermediate_output=-2)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/comfy/clip_model.py", line 186, in forward
    x = self.vision_model(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/comfy/clip_model.py", line 175, in forward
    x, i = self.encoder(x, mask=None, intermediate_output=intermediate_output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/comfy/clip_model.py", line 68, in forward
    x = l(x, mask, optimized_attention)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/comfy/clip_model.py", line 49, in forward
    x += self.self_attn(self.layer_norm1(x), mask, optimized_attention)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/comfy/clip_model.py", line 20, in forward
    out = optimized_attention(q, k, v, self.heads, mask)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ComfyUI/comfy/ldm/modules/attention.py", line 313, in attention_pytorch
    q, k, v = map(
    ^^^^^^^
  File "/tmp/ComfyUI/comfy/ldm/modules/attention.py", line 314, in <lambda>
    lambda t: t.view(b, -1, heads, dim_head).transpose(1, 2),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1, 16, 80] because the unspecified dimension size -1 can be any value and is ambiguous
```

</details>

is it possible to use batch size more than 1?

using intel gpu and pytorch 2.1.1 with intel patches

**Comment by fractal-fumbler** [comment]
solved with node `Repeat image batch`
